//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGCourries.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArriveeDocs
    {
        public int idArriveeDocs { get; set; }
        public int idArrivee { get; set; }
        public string TypeDocArrivee { get; set; }
        public byte[] ContenuFileArrivee { get; set; }
        public string FileName { get; set; }
    
        public virtual Arrivee Arrivee { get; set; }
    }
}
