//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGCourries.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Depart()
        {
            this.DepartDocs = new HashSet<DepartDocs>();
            this.Entites = new HashSet<Entites>();
        }
    
        public int idDepart { get; set; }
        public int idCateg { get; set; }
        public int idUser { get; set; }
        public int Annee { get; set; }
        public int NumOrdre { get; set; }
        public System.DateTime DateOrdre { get; set; }
        public string Sujet { get; set; }
        public string Ramarques { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual TUsers TUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartDocs> DepartDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entites> Entites { get; set; }
    }
}
