//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGCourries.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartDocs
    {
        public int idDocDepart { get; set; }
        public int idDepart { get; set; }
        public string TypeDocDepart { get; set; }
        public byte[] ContenuFileDepart { get; set; }
    
        public virtual Depart Depart { get; set; }
    }
}
